import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import "./styles/globals.css";
import { Analytics } from "@vercel/analytics/react"
import Link from "next/link";
import "./styles/font.css"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const menuItem = (url: string, text: string, className?: string) => (
    <div className={className}>
      <Link href={url}>{text}</Link>
    </div>
  );

  return (
    <html lang="en" className="SourceSerif">
      <body>
        {children}
        <Analytics/>
      </body>
    </html>
  );
}