import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import "./styles/globals.css";
import Link from "next/link";

const inter = GeistSans;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const menuItem = (url: string, text: string, className?: string) => (
    <div className={className}>
      <Link href={url}>{text}</Link>
    </div>
  );

  return (
    <html lang="en" className="scroll-smooth">
      <body className="container mx-auto py-[10px]">
        <div className="box-border w-full p-4 border-4 sticky top-5 py-[20px] backdrop-blur-sm bg-white/30 z-50 border-transparent rounded-full"> 
          <div className="inline-flex w-full justify-between">
            {menuItem('#muhammadakfz', 'muhammadakfz', "font-bold")}
            <div className='inline-flex space-x-10 justify-end pe-10px'>
              {menuItem('#about', 'About', "font-normal hover:font-bold")}
              {menuItem('/', 'Contact', "font-normal hover:font-bold")}
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}